server.port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
