server.port: 8080
springdoc:
  swagger-ui:
    path: /docs-academia.html
  api-docs:
    path: /docs-academia
  packagesToScan: br.com.brunostaine.academia.controllers
spring:
  web:
    locale-resolver: fixed
    locale: pt_BR
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
